"""create_tabla_usuario

Revision ID: 8feaeb44e262
Revises: 
Create Date: 2026-03-21 19:54:43.566687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8feaeb44e262'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ap_pat', sa.String(length=100), nullable=False),
    sa.Column('ap_mat', sa.String(length=100), nullable=True),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('contraseña', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('f_nacimiento', sa.Date(), nullable=True),
    sa.Column('telefono', sa.String(length=10), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuario_usuario'), 'usuario', ['usuario'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_usuario'), table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
